# Generated by Django 3.2.5 on 2022-09-16 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_todo_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='color',
        ),
    ]
